### ISSUE TITLE
Test codejail on Python 3.11

### ISSUE THREAD

**Issue by feanil** [openedx/codejail#165]
This repository is a depedency of edx-platform and needs to be upgraded to Python 3.11 before
the Readwood release is cut (mid-April).

- [x] Requirements are compiled with Python 3.8
- [x] Tests are run on Python 3.8 and 3.11
- [ ] (Optional) Tests are also run with 3.12 and passing or 3.12 issues are ticketed.
- [ ] Classifiers in setup.py setup.cfg or pyproject.toml indicate Python 3.11 support
- [x] A new version is release to PyPI
- [ ] A PR is merged to edx-platform to use the new version

**Comment by kdmccormick** [comment]
This ticket will handle upgrading codejail itself to 3.11. As a follow-up, we will need to upgrade edx-platform's codejail execution environment (a.k.a. edx-sandbox) to Python 3.11/3.12: https://github.com/openedx/edx-platform/issues/34469

**Comment by ichintanjoshi** [comment]
assign me

**Comment by MoisesGSalas** [comment]
Hi @feanil, I would like to help on the 3.11 upgrade. If you are lacking on bandwidth I can take on this issue. Or if you need help somewhere else I can give a hand.

**Comment by MoisesGSalas** [comment]
I was focusing on this one because I was recently appointed as maintainer for the codejail repo, so I would really like to one something related to it to get more familiar (even if it's not this specific task).

I do have a bit of experience running codejail (mostly k8s) so I would like to hear any recommendation on where I can help. (I can still check the credentials one, but literally have 0 experience with that service).

**Comment by feanil** [comment]
Ah, gotcha, @MoisesGSalas take a look at https://github.com/openedx/codejail/pull/167  please review.
